### ISSUE TITLE
Eager loading not working when executing `scout:import` command

### ISSUE THREAD

**Issue by andrey-helldar** [babenkoivan/elastic-scout-driver-plus#149]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 8.1.17
| Elasticsearch            | 8.6.1
| Laravel                      | 9.52.4
| Laravel Scout           | 10.0.2
| Elastic Scout Driver | 4.3.0

**Describe the bug**
Eager loading not working when executing `scout:import` command.

**To Reproduce**
```php
// It's works
User::query()
        ->get()
        ->searchable();

// Doesn't works
php artisan scout:import App\\Models\\User
```
![image](https://user-images.githubusercontent.com/10347617/225954953-3319fd9d-e6b4-4e91-90e1-44a4a3890831.png)

**Current behavior**
When calling the console command, the `searchableWith` method is called for each specific model instead of the builder, which is why eager loading for a collection of models does not work because the `loadMissing` method called on the model parses the names for each model:

https://github.com/babenkoivan/elastic-scout-driver-plus/blob/6beb9fdcc2b5c498d130da7bc2d5a213905d186b/src/Factories/DocumentFactory.php#L15-L17

https://github.com/laravel/framework/blob/c3e679cc7d19527fda4210ef137075dafb106d0c/src/Illuminate/Database/Eloquent/Collection.php#L193-L215

https://github.com/laravel/framework/blob/c3e679cc7d19527fda4210ef137075dafb106d0c/src/Illuminate/Database/Eloquent/Collection.php#L237

**Expected behavior**
Eager loading will work.

**Current hotfix**
I created a trait and overridden the `makeAllSearchableUsing` method in it:

```php
namespace App\Scout;

use Elastic\ScoutDriverPlus\Searchable as BaseSearchable;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;

trait Searchable
{
    use BaseSearchable;

    protected function makeAllSearchableUsing(EloquentBuilder $query): EloquentBuilder
    {
        return $query->with(
            $this->searchableWith()
        );
    }
}
```

With this approach, eager loading works without problems because:

https://github.com/laravel/scout/blob/faff096e9e93ee087782a89917472f3452cc933b/src/Searchable.php#L141-L151

**Comment by babenkoivan** [comment]
Hi @andrey-helldar, thank you for opening this issue! 

I couldn't confirm that the problem is related to `DocumentFactory`. From what I can see in the code, it works the same when you call `searchable()` and `makeAllSearchable()`, but I found another issue. 

If you use custom routing (i.e. `Searchable::searchableRouting()`) and it depends on searchable relations, then you might see a huge amount of queries because these relations are not preloaded. I've fixed this in [v4.3.1](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v4.3.1). Can you please update the package and see if your initial problem is resolved?

**Comment by andrey-helldar** [comment]
No, the problem persists.

Here are my steps:

1. Create index

```php
use Elastic\Adapter\Indices\Mapping;
use Elastic\Adapter\Indices\Settings;
use Elastic\Migrations\Facades\Index;
use Elastic\Migrations\MigrationInterface;

class Temp implements MigrationInterface
{
    public function up()
    {
        Index::create('cities', function (Mapping $map, Settings $settings) {
            $map->long('id');
            $map->text('title');

            $settings->index(config('elastic.migrations.settings.index'));
            $settings->analysis(config('elastic.migrations.settings.analysis'));
        });
    }

    public function down()
    {
        Index::dropIfExists('cities');
    }
}
```

2. My trait:

```php
namespace App\Scout;

use Elastic\ScoutDriverPlus\Searchable as BaseSearchable;
use Illuminate\Database\Eloquent\Builder as EloquentBuilder;

trait Searchable
{
    use BaseSearchable;

    protected function makeAllSearchableUsing(EloquentBuilder $query): EloquentBuilder
    {
        if ($relations = $this->searchableWith()) {
            return $query->with($relations);
        }

        return $query;
    }
}
```

4. Attach trait to model:

```php
use App\Scout\Searchable;

class City extends Model
{
    use Searchable;
}
```

5. Run the console command:
```bash
$ art scout:import App\\Models\\City

Imported [App\Models\City] models up to ID: 100
Imported [App\Models\City] models up to ID: 129

All [App\Models\City] records have been imported.
```

**BUT** now the behavior is completely different.

Now, after I updated the application, it works like this:

When I override the `makeAllSearchableUsing` method, I get duplicate requests as a result:

![image](https://user-images.githubusercontent.com/10347617/228348371-19b7a973-fca7-4a6f-9300-f3efa8d2128c.png)

And when I disable this method (commented it out), then the duplicates disappear, therefore, eager loading works correctly.

![image](https://user-images.githubusercontent.com/10347617/228348717-bc9ede6e-e02d-44e1-bae9-37694261405f.png)

Before the package update, it was exactly the opposite.

So I think the problem can be considered closed :)
